# Análise de Gastos dos Deputados Federais - Legislatura 57

## Consumindo as tabelas e modificando colunas

In [42]:
import pandas as pd

In [56]:
database_gastos = pd.read_csv('/home/eduardo/documentos/pipelines_dados_politica/database/merged_despesas_final_completa.csv')
database_deputados_id_legis_57 = pd.read_csv('/home/eduardo/documentos/pipelines_dados_politica/database/deputados_2026_id_legis_57.csv')
database_deputados_snapshot = pd.read_csv('/home/eduardo/documentos/pipelines_dados_politica/database/deputados_2026.csv')

In [61]:
database_deputados_id_legis_57.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639 entries, 0 to 638
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             639 non-null    int64
 1   uri            639 non-null    object
 2   nome           639 non-null    object
 3   siglaPartido   639 non-null    object
 4   uriPartido     639 non-null    object
 5   siglaUf        639 non-null    object
 6   idLegislatura  639 non-null    int64
 7   urlFoto        639 non-null    object
 8   email          513 non-null    object
dtypes: int64(2), object(7)
memory usage: 45.1+ KB

In [45]:
database_deputados_snapshot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 513 entries, 0 to 512
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             513 non-null    int64
 1   uri            513 non-null    object
 2   nome           513 non-null    object
 3   siglaPartido   513 non-null    object
 4   uriPartido     513 non-null    object
 5   siglaUf        513 non-null    object
 6   idLegislatura  513 non-null    int64
 7   urlFoto        513 non-null    object
 8   email          513 non-null    object
dtypes: int64(2), object(7)
memory usage: 36.2+ KB

In [46]:
database_gastos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643309 entries, 0 to 643308
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ano                643309 non-null  int64
 1   mes                643309 non-null  int64
 2   tipoDespesa        643309 non-null  object
 3   codDocumento       643309 non-null  object
 4   tipoDocumento      643309 non-null  object
 5   codTipoDocumento   643309 non-null  int64
 6   dataDocumento      643309 non-null  object
 7   numDocumento       643285 non-null  object
 8   valorDocumento     643309 non-null  float64
 9   urlDocumento       450552 non-null  object
 10  nomeFornecedor     643309 non-null  object
 11  cnpjCpfFornecedor  474198 non-null  float64
 12  valorLiquido       643309 non-null  float64
 13  valorGlosa         643309 non-null  float64
 14  numRessarcimento   175733 non-null  float64
 15  codLote            643309 non-null  int64
 16  parcela            643309 non-null  int64
 17  id_deputado        643309 non-null  int64
dtypes: float64(5), int64(6), object(7)
memory usage: 88.3+ MB

### Ajuste nas Colunas

In [47]:
database_gastos = database_gastos.merge(
    database_deputados_id_legis_57[['id', 'nome', 'siglaPartido', 'siglaUf']],
    left_on='id_deputado',
    right_on='id',      
    how='left'  
)

In [48]:
database_gastos['dataDocumento'] = pd.to_datetime(database_gastos['dataDocumento'])

database_gastos['dataDocumento_dd/mm/yyyy'] = database_gastos['dataDocumento'].dt.date

In [49]:
database_gastos['ano_mes'] = (
    database_gastos['ano'].astype(str)
    + '-'
    + database_gastos['mes'].astype(str)
)

In [50]:
database_gastos = database_gastos[['nome', 'id_deputado' , 'siglaPartido', 'siglaUf','tipoDespesa', 'tipoDocumento', 'valorDocumento',
       'codDocumento', 'codTipoDocumento', 'dataDocumento', 'numDocumento', 
       'urlDocumento', 'nomeFornecedor', 'cnpjCpfFornecedor', 'valorLiquido',
       'valorGlosa', 'numRessarcimento', 'codLote', 'parcela',
       'dataDocumento_dd/mm/yyyy', 'ano', 'mes', 'ano_mes']]

In [51]:
database_gastos.head(10)

,nome,id_deputado,siglaPartido,siglaUf,tipoDespesa,tipoDocumento,valorDocumento,codDocumento,codTipoDocumento,dataDocumento,...,cnpjCpfFornecedor,valorLiquido,valorGlosa,numRessarcimento,codLote,parcela,dataDocumento_dd/mm/yyyy,ano,mes,ano_mes
0,Acácio Favacho,204379,MDB,AP,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,Nota Fiscal,25000.00,7509529,0,2023-03-14,...,2.671184e+13,25000.00,0.0,NaN,1914633,0,2023-03-14,2023,1,2023-1
1,Acácio Favacho,204379,MDB,AP,TELEFONIA,Nota Fiscal,353.70,0,0,2023-02-15,...,1.000000e+00,353.70,0.0,0.0,0,0,2023-02-15,2023,1,2023-1
2,Acácio Favacho,204379,MDB,AP,TELEFONIA,Nota Fiscal,116.43,0,0,2023-02-14,...,1.000000e+00,116.43,0.0,0.0,0,0,2023-02-14,2023,1,2023-1
3,Acácio Favacho,204379,MDB,AP,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,Nota Fiscal,10000.00,7506338,0,2023-02-02,...,1.514482e+13,10000.00,0.0,NaN,1912967,0,2023-02-02,2023,1,2023-1
4,Acácio Favacho,204379,MDB,AP,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,Nota Fiscal Eletrônica,809.60,7520851,4,2023-03-28,...,3.237381e+13,809.60,0.0,NaN,1921029,0,2023-03-28,2023,3,2023-3
5,Acácio Favacho,204379,MDB,AP,COMBUSTÍVEIS E LUBRIFICANTES.,Nota Fiscal,221.98,7504667,0,2023-02-23,...,3.065970e+11,221.98,0.0,NaN,1915529,0,2023-02-23,2023,2,2023-2
6,Acácio Favacho,204379,MDB,AP,COMBUSTÍVEIS E LUBRIFICANTES.,Nota Fiscal Eletrônica,283.97,7511136,4,2023-02-28,...,3.065970e+11,283.97,0.0,NaN,1915531,0,2023-02-28,2023,2,2023-2
7,Acácio Favacho,204379,MDB,AP,COMBUSTÍVEIS E LUBRIFICANTES.,Nota Fiscal Eletrônica,299.98,7520880,4,2023-03-20,...,3.065970e+11,299.98,0.0,NaN,1921040,0,2023-03-20,2023,3,2023-3
8,Acácio Favacho,204379,MDB,AP,COMBUSTÍVEIS E LUBRIFICANTES.,Nota Fiscal Eletrônica,100.04,7564652,4,2023-05-31,...,3.065970e+11,100.04,0.0,NaN,1945830,0,2023-05-31,2023,5,2023-5
9,Acácio Favacho,204379,MDB,AP,COMBUSTÍVEIS E LUBRIFICANTES.,Nota Fiscal Eletrônica,150.00,7572166,4,2023-07-05,...,3.065970e+11,150.00,0.0,NaN,1949433,0,2023-07-05,2023,7,2023-7

## Analise de Agrupamentos

### A grupamento por Deputado

In [52]:
agrupado_por_deputado = (
    database_gastos.groupby(
        ['nome','id_deputado', 'siglaPartido', 'siglaUf'],
        as_index=False
    ).agg(
        total_gasto=('valorDocumento', 'sum'),
        media_gasto=('valorDocumento', 'mean'),
        qtd_notas=('numDocumento', 'count'),
        qtd_meses_com_gasto=('ano_mes', 'nunique')
    )
).round(2)

agrupado_por_deputado['media_mensal_gasto'] = (
    agrupado_por_deputado['total_gasto'] / agrupado_por_deputado['qtd_meses_com_gasto']
).round(2)


agrupado_por_deputado.head(10)

,nome,id_deputado,siglaPartido,siglaUf,total_gasto,media_gasto,qtd_notas,qtd_meses_com_gasto,media_mensal_gasto
0,AJ Albuquerque,204549,PP,CE,1150438.80,1372.84,838,40,28760.97
1,ANDRÉ ABDON,178831,PP,AP,423973.68,1605.96,264,10,42397.37
2,Acácio Favacho,204379,MDB,AP,1892367.64,1683.60,1124,40,47309.19
3,Adail Filho,220714,REPUBLICANOS,AM,1852575.66,2534.30,731,39,47501.94
4,Adilson Barroso,221328,PL,SP,1642618.52,1006.51,1632,39,42118.42
5,Adolfo Viana,204560,PSDB,BA,1524642.93,1947.18,783,39,39093.41
6,Adriana Ventura,204528,NOVO,SP,254281.77,225.03,1130,39,6520.05
7,Adriano do Baldy,121948,PP,GO,1645356.15,960.51,1713,40,41133.90
8,Afonso Florence,160508,PT,BA,22121.99,1382.62,16,5,4424.40
9,Afonso Hamm,136811,PP,RS,673096.47,540.64,1245,25,26923.86

### Agrupamento por Partido

In [53]:
gastos_partido = (
    agrupado_por_deputado.groupby('siglaPartido')
    .agg({
        'total_gasto':'sum',
        'media_mensal_gasto':'mean',
        'id_deputado':'count'
    }).round(2)
    .rename(columns={'id_deputado':'qtd_deputados'})
).sort_values('total_gasto', ascending=False)

gastos_partido['media_gasto_por_deputado'] = (
    gastos_partido['total_gasto'] / gastos_partido['qtd_deputados']
).round(2)


gastos_partido

,total_gasto,media_mensal_gasto,qtd_deputados,media_gasto_por_deputado
siglaPartido,,,,
PL,1.415441e+08,38878.58,97,1459217.96
PT,1.028561e+08,40474.79,66,1558425.46
UNIÃO,8.514541e+07,40325.92,58,1468024.28
PP,6.522900e+07,38370.45,47,1387851.05
MDB,6.186074e+07,40068.82,41,1508798.45
PSD,5.816686e+07,38830.86,42,1384925.25
REPUBLICANOS,5.580988e+07,38391.22,39,1431022.57
PDT,2.468819e+07,42616.07,16,1543012.09
PSB,2.361145e+07,41361.98,15,1574096.92
PSDB,2.190271e+07,39709.18,14,1564479.29
PODE,1.935081e+07,40451.83,14,1382200.74
PSOL,1.530018e+07,35647.21,11,1390925.78
PCdoB,1.237937e+07,39423.56,9,1375485.25
PV,1.014997e+07,42800.33,6,1691662.11
AVANTE,8.671943e+06,32184.35,7,1238848.99
PSC,7.882116e+06,36115.89,6,1313686.01
SOLIDARIEDADE,5.707510e+06,39073.58,4,1426877.51
PROS,4.967862e+06,42132.01,3,1655953.88
PATRIOTA,4.578949e+06,38880.23,4,1144737.18
CIDADANIA,3.942428e+06,25187.06,4,985607.00
NOVO,1.701274e+06,14540.81,3,567091.50
REDE,1.672506e+06,32688.87,2,836252.86
PTB,1.666257e+06,42724.54,1,1666257.24

### Agrupamento por UF

In [54]:
gastos_uf = (
    agrupado_por_deputado.groupby('siglaUf')
    .agg({
        'total_gasto':'sum',
        'media_mensal_gasto':'mean',
        'id_deputado':'count'
    }).round(2)
    .rename(columns={'id_deputado':'qtd_deputados'})
).sort_values('total_gasto', ascending=False)

gastos_uf['media_gasto_por_deputado'] = (
    gastos_uf['total_gasto'] / gastos_uf['qtd_deputados']
).round(2)


gastos_uf

,total_gasto,media_mensal_gasto,qtd_deputados,media_gasto_por_deputado
siglaUf,,,,
SP,89781818.44,35628.69,68,1320320.86
MG,78260997.42,37830.85,53,1476622.59
RJ,60872997.48,36132.31,46,1323326.03
BA,57769280.98,38345.32,39,1481263.61
RS,44002119.72,38139.09,31,1419423.22
PR,42953724.81,39407.52,30,1431790.83
PE,41510866.91,43087.74,25,1660434.68
CE,31368607.82,42684.11,21,1493743.23
PA,25439021.81,39497.08,17,1496413.05
GO,23815893.11,36608.60,17,1400934.89
SC,22118623.75,36935.06,16,1382413.98
MA,21701412.20,39520.45,18,1205634.01
PB,20744628.19,44416.87,12,1728719.02
PI,17774088.44,45804.80,10,1777408.84
ES,15892947.44,40423.46,10,1589294.74
RR,15544124.09,49715.20,8,1943015.51
MS,14297240.01,44969.60,8,1787155.00
AC,13808642.74,48854.24,8,1726080.34
AL,13549264.53,38649.47,9,1505473.84
RO,13413792.41,46315.11,8,1676724.05
RN,13005350.65,44199.65,8,1625668.83
SE,12070003.26,41163.02,8,1508750.41
TO,11595172.04,40937.93,8,1449396.50
AM,9949639.28,40026.49,7,1421377.04
MT,9812971.61,38205.68,8,1226621.45
DF,9382664.04,32864.58,8,1172833.00
AP,8349749.21,34514.31,8,1043718.65

### Documentos compartilhados por Deputados

In [75]:
database_gastos[
    database_gastos['numDocumento'].duplicated(keep=False)
]

,ano,mes,tipoDespesa,codDocumento,tipoDocumento,codTipoDocumento,dataDocumento,numDocumento,valorDocumento,urlDocumento,nomeFornecedor,cnpjCpfFornecedor,valorLiquido,valorGlosa,numRessarcimento,codLote,parcela,id_deputado
0,2023,1,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,7509529,Nota Fiscal,0,2023-03-14T00:00:00,315,25000.00,https://www.camara.leg.br/cota-parlamentar/doc...,I. RODRIGUES DE ALMEIDA,2.671184e+13,25000.00,0.0,NaN,1914633,0,204379
1,2023,1,TELEFONIA,0,Nota Fiscal,0,2023-02-15T00:00:00,7526639,353.70,NaN,CELULAR FUNCIONAL,1.000000e+00,353.70,0.0,0.0,0,0,204379
2,2023,1,TELEFONIA,0,Nota Fiscal,0,2023-02-14T00:00:00,7526961,116.43,NaN,CELULAR FUNCIONAL,1.000000e+00,116.43,0.0,0.0,0,0,204379
4,2023,3,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,7520851,Nota Fiscal Eletrônica,4,2023-03-28T00:00:00,42,809.60,http://www.camara.leg.br/cota-parlamentar/nota...,EDVALDO FRANCISCO DE OLIVEIRA 49191160120,3.237381e+13,809.60,0.0,NaN,1921029,0,204379
6,2023,2,COMBUSTÍVEIS E LUBRIFICANTES.,7511136,Nota Fiscal Eletrônica,4,2023-02-28T00:00:00,299904,283.97,http://www.camara.leg.br/cota-parlamentar/nota...,031 - 302 NORTE - CASCOL COMBUSTIVEIS PARA VEI...,3.065970e+11,283.97,0.0,NaN,1915531,0,204379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643295,2026,3,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",8064448,Nota Fiscal,0,2026-03-10T00:00:00,997,850.40,https://www.camara.leg.br/cota-parlamentar/doc...,INTER-OCEANICA HOTELARIA E TURISMO LTDA - ME,1.282631e+13,850.40,0.0,NaN,2216831,0,220592
643296,2026,1,LOCAÇÃO OU FRETAMENTO DE AERONAVES,8040836,Nota Fiscal,0,2026-01-20T00:00:00,1170,8000.00,https://www.camara.leg.br/cota-parlamentar/doc...,AEROBRAN TAXI AERO LTDA,7.918532e+12,8000.00,0.0,NaN,2203463,0,220592
643297,2026,1,LOCAÇÃO OU FRETAMENTO DE AERONAVES,8057956,Nota Fiscal,0,2026-03-02T00:00:00,1178,6500.00,https://www.camara.leg.br/cota-parlamentar/doc...,AEROBRAN TAXI AERO LTDA,7.918532e+12,6500.00,0.0,NaN,2213135,0,220592
643299,2026,1,PASSAGEM AÉREA - SIGEPA,A18890ED-3A4F-446B-BFAB-C91D915D4D4B,Nota Fiscal,0,2026-01-13T00:00:00,1272153489951,85.00,NaN,Gol Linhas Aéreas,NaN,85.00,0.0,0.0,0,0,220592
643300,2026,1,PASSAGEM AÉREA - SIGEPA,A18890ED-3A4F-446B-BFAB-C91D915D4D4B,Nota Fiscal,0,2026-01-13T00:00:00,1272153489951,1239.74,NaN,Gol Linhas Aéreas,NaN,1239.74,0.0,0.0,0,0,220592